### ISSUE TITLE
Can't create user!!!! help!!

### ISSUE THREAD

**Issue by Mamta24a** [GautamAnghore/clic-o-matic#1]
On running run.exe, and after login this issue is occurring :
User creation failed, internal error
please help!!

**Comment by GautamAnghore** [comment]
Hi, Thanks for looking into this.
Error reporting is not proper yet. This error mostly occur if you are trying to create a duplicate user. You can check the development server log, it might give you proper error like `duplicate user`
![clic-o-matic](https://cloud.githubusercontent.com/assets/7152214/8888336/288f6b9c-32c7-11e5-9f7c-6f28a761bbdb.png)
If that is the case, please login instead of signup or try to create a different user.
Also, please pull the latest changes before trying. If you face any more difficulty, I'll be happy to help.
Thanks.

**Comment by Mamta24a** [comment]
Thank you for your reply sir!!!
Yes, this was my previous issue but after logging in with same user. I got  this error:
![capture](https://cloud.githubusercontent.com/assets/12842137/8889400/9b54762e-328e-11e5-842d-6ede7f5cc4f1.PNG)
and now after trying again with new user, the login page is not opening...on clicking the "Get started" or "Login" button, nothing is opening just that page gets refreshed again and again.

**Comment by GautamAnghore** [comment]
Can you please try to sign in **after pulling the new commits**?
If the error still exists, can you please provide the full error (the image you pasted does not gives the full log).

**Comment by Mamta24a** [comment]
On pulling new commits. Its showing "already up-to-date" message and still the same issue is occurring.
![capture](https://cloud.githubusercontent.com/assets/12842137/8894286/59c6ef5c-3365-11e5-8751-ff12a615c288.PNG)
On this page after clicking either of the buttons, the same page gets refreshed. The login page or sign up page is not opening.

**Comment by GautamAnghore** [comment]
First of all, you can check if you have the latest commit pulled or not. Do `git log` and check the latest commit. It should be `redirection bug fix`. 
If its not, you must be pulling from your fork of the repository. You must pull from this repository.
Check the origin of your repository by - 
`git config --get remote.origin.url`
and if it is not `https://github.com/GautamAnghore/clic-o-matic`, you need to add it as upstream by -
`git remote add upstream https://github.com/GautamAnghore/clic-o-matic`.
Then pull from upsteram -
`git pull upstream master`.
I think this will solve the problem. The latest commit was exactly to solve the problem you mentioned.

**Comment by Mamta24a** [comment]
Even after pulling new commits...Still getting the same issue. :/

**Comment by GautamAnghore** [comment]
I am not able to reproduce the error. The new commits modifies the redirection link if there is no page added to monitor.
Can you please try to login after clearing the cache?
If the error is still not solved, can you please share your `git log` and the server log using a pastebin?

**Comment by Mamta24a** [comment]
whooa... After clearing the cache, It's working 
Thank you sooo much sir.  :) :)

**Comment by GautamAnghore** [comment]
Thats great. Thank you for looking into this and reporting the issue.
