### ISSUE TITLE
Not working for other webpages...except test-webpage

### ISSUE THREAD

**Issue by Mamta24a** [GautamAnghore/clic-o-matic#2]
Sir, Again I'm facing a problem. This tool is only working for the given test-webpage sample, and its also not opening the site in full screen. 
![capture](https://cloud.githubusercontent.com/assets/12842137/8969031/b0b68934-35f5-11e5-8c14-4f78762fc4a6.PNG)
It is not showing the clicks or heatmap of the added webpage.

**Comment by GautamAnghore** [comment]
Have you pasted the code given during `add page` option on the page you want to trace (Javascript Tutorial page in this case)?

![clic-o-matic-script](https://cloud.githubusercontent.com/assets/7152214/8984022/61f06336-36ec-11e5-95f3-4481f94a14ee.png)

**Comment by GautamAnghore** [comment]
One Important thing to remember here is that the tool is for the websites(specifically webpages) **you** own or have authority to modify the source code. The data of clicks for a webpage can be traced only if that webpage is able to send data to this app and that is what the activation code do. 

Also if you want to use this in production, be sure about the security issues this tool might have.

**Comment by Mamta24a** [comment]
Yea, okay sir. I got it.
Thank you for the help. :)
